root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  "testdata",
  "web/public",
  "web/node_modules",
  "web/dist",
  "public",
  "docs",
  "dev",
  "dist",
]
args_bin = []
bin = "./tmp/main -config dev/tailnet-local.yaml"
cmd = "templ generate --notify-proxy & go build -o ./tmp/main cmd/server/main.go"
delay = 1000
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl"]
include_file = []
kill_delay = "1s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
