services:
  tailnet-lib:
    build: .
    image: ghcr.io/sudosu404/tailnet-lib:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/config
    restart: unless-stopped

volumes:
  datadir:
